"""
idiomas.py
----------
Sistema de idiomas de la app: diccionario de textos (español / inglés /
portugués) + helpers para consultar y cambiar el idioma activo.

Cómo se usa en el resto del código:

    from setup.idiomas import tr, IDIOMAS_DISPONIBLES, establecer_idioma

    grupo = QGroupBox(tr("ajustes_teclas_titulo"))

Agregar una traducción nueva: sumá la clave a los 3 diccionarios de
TEXTOS (es / en / pt). Si un idioma no tiene esa clave todavía, tr()
cae automáticamente al texto en español -- así la interfaz nunca se
rompe ni queda con un hueco por una traducción que falte mientras se
sigue ampliando la cobertura al resto del programa.

Este es el punto de partida del sistema de idiomas: por ahora cubre
la ventana de Ajustes (donde vive el selector). El resto de la app
(ventana principal, lista de temas) se va a ir sumando acá mismo.
"""

IDIOMA_POR_DEFECTO = "es"

IDIOMAS_DISPONIBLES = {
    "es": "Español",
    "en": "English",
    "pt": "Português",
}

TEXTOS = {
    "es": {
        "ajustes_titulo_ventana": "⚙ Ajustes - Smart AI DJ Mixer",
        "ajustes_teclas_titulo": "🎹 Teclas de mezcla",
        "ajustes_volumen_titulo": "🔊 Volumen",
        "ajustes_brillo_titulo": "✨ Brillo y golpe",
        "ajustes_cruce_titulo": "🎚️ Cruce",
        "ajustes_efectos_titulo": "🎛️ Efectos en vivo",
        "ajustes_zona_titulo": "🎯 Zona de mezcla",
        "ajustes_orden_titulo": "🔀 Orden y carga",
        "ajustes_estilo_titulo": "🎨 Estilo visual",
        "ajustes_historial_titulo": "📄 Historial",
        "ajustes_cerrar_titulo": "✔ Cerrar",
        "ajustes_restaurar_titulo": "↺ Valores por defecto",
        "ajustes_golpe_seco_titulo": "🥁 Golpe seco",
        "ajustes_idioma_titulo": "🌐 Idioma",
        "ajustes_idioma_etiqueta": "Idioma:",
        "ajustes_idioma_nota": "Se aplica al reiniciar el programa.",
        "boton_cerrar": "Cerrar",
        "boton_restaurar_todo": "↺ Restaurar todo",
        "boton_abrir_carpeta_estilos": "📂 Abrir carpeta de estilos",
        "boton_crear_skin": "🎨 Crear skin",
        "boton_exportar_historial": "📄 Exportar historial del set",
        "boton_acerca_de": "ℹ️ Acerca de",
        "skin_lista_titulo": "Lista de temas -- flecha = qué color cambia",
        "skin_bordes_titulo": "Bordes -- flecha = qué color cambia",
        "skin_volumen_titulo": "Volumen -- flecha = qué color cambia",

        # --- Ventana principal (SmartDJPlayer / Principal.py) ---
        "ppal_tooltip_minimizar": "Minimizar",
        "ppal_tooltip_cerrar_ventana": "Cerrar",
        "ppal_overlay_analizando": "⏳ Analizando temas, esperá un momento...",
        "ppal_lista_recuperada": "Lista recuperada de la sesión anterior ({n} pistas).",
        "ppal_lista_vacia_arrastra": "Lista vacía. Arrastrá archivos o usá 📂 Cargar carpeta.",
        "ppal_deck_a_vacio": "Deck A: (sin tema)",
        "ppal_deck_b_vacio": "Deck B: (sin tema en espera)",
        "ppal_deck_a_nombre": "Deck A",
        "ppal_deck_b_nombre": "Deck B",
        "ppal_sin_datos": "Sin datos",
        "ppal_volumen_master_etiqueta": "Volumen Master:",
        "ppal_tooltip_volumen_master": "Volumen general de la salida. Afecta a A y a B por igual.",
        "ppal_tooltip_btn_config": "Abrir Ajustes (teclas, normalizador, brillo, cruce, efectos, orden, carga).",
        "ppal_estado_prefijo": "Estado",
        "ppal_estado_inicial": "Esperando música...",
        "ppal_pista_actual_prefijo": "Pista actual",
        "ppal_pista_actual_ninguna": "Ninguna",
        "ppal_tooltip_prev": "Mezclar hacia el tema anterior (adelanta el recuadro a la próxima frase).",
        "ppal_tooltip_next": "Mezclar hacia el tema siguiente (adelanta el recuadro a la próxima frase).",
        "ppal_tooltip_play": "Reproducir / Pausar.",
        "ppal_tooltip_stop": "Primer click: pausa (no saca los temas de las bandejas).\nSegundo click (ya detenido): vacía las bandejas y vuelve\nal principio de la lista.",
        "ppal_btn_limpiar_lista": "🗑 Limpiar lista",
        "ppal_tooltip_limpiar_lista": "Elimina todos los temas de la lista (pide confirmación).",
        "ppal_btn_reordenar_auto": "🔀 Reordenar auto",
        "ppal_tooltip_reordenar_auto": "Vuelve a ordenar toda la lista automáticamente (según BPM o Tono,\nlo que tengas elegido en Ajustes) y reactiva el orden automático,\nque se apaga cuando movés temas a mano.",
        "ppal_btn_ocultar_lista": "📋 Ocultar lista",
        "ppal_btn_mostrar_lista": "📋 Mostrar lista",
        "ppal_tooltip_mostrar_lista": "Muestra u oculta la ventana de la lista de temas (que vive\naparte, pegada por defecto abajo del reproductor). Si la\nacercás a cualquier borde del reproductor se encastra ahí\nsola (imán) y viaja pegada de ahí en más; se despega\narrastrándola lejos.",
        "ppal_chk_auto": "Auto",
        "ppal_tooltip_modo_mezcla": "Auto: los temas se mezclan con crossfade al llegar al\nrecuadro amarillo (modo mezcla automática).\nMan: cada tema termina y pasa directo al siguiente,\nsin cruce ni recuadro (modo manual).",
        "ppal_tooltip_waveform_next": "Arrastrá el recuadro amarillo para mover a mano el punto\ndonde este tema entra en la próxima mezcla.",
        "ppal_tooltip_golpe_seco_barra": "Golpe seco: nivel de energía del bombo (banda 60-120 Hz)\ndel tema entrante, medido en vivo. Se ilumina cuando hay\ngolpe de bombo y baja solo entre golpes.",
        "ppal_status_aleatorio_on": "🔀 Modo aleatorio activado.",
        "ppal_status_aleatorio_off": "☰ Modo aleatorio desactivado, la lista vuelve a su orden normal.",
        "ppal_status_no_audios": "No se encontraron audios en {carpeta}",
        "ppal_status_orden_manual_actualizado": "✋ Orden manual actualizado.",
        "ppal_status_orden_auto_desactivado": "✋ Moviste un tema a mano. Orden automático desactivado (usá 🔀 Reordenar auto para volver a activarlo).",
        "ppal_status_lista_vacia_ordenar": "No hay temas en la lista para ordenar.",
        "ppal_status_orden_auto_tono": "🔀 Orden automático reactivado (por Tono).",
        "ppal_status_orden_auto_bpm": "🔀 Orden automático reactivado (por BPM).",
        "ppal_status_lista_vacia": "Lista vacía.",
        "ppal_status_temas_eliminados": "🗑️ Se eliminaron {n} temas de \"{grupo}\".",
        "ppal_status_error_reproducir": "❌ Error al reproducir: {err}",
        "ppal_status_error_inesperado": "❌ Error inesperado: {err}",
        "ppal_status_ordenando_tono_fondo": "🎧 Ordenando por tono en segundo plano...",
        "ppal_status_todos_saltear": "⛔ Todos los temas de la lista están marcados para saltear.",
        "ppal_status_punto_enganche": "Punto de enganche movido al {pct}% del tema. Se guardará para los próximos temas.",
        "ppal_status_punto_entrada_b": "📍 Punto de entrada de B movido a mano ({seg}s). Reprocesando...",
        "ppal_status_nada_nuevo": "No se agregó nada nuevo: {n} tema(s) ya estaban en la lista o eran duplicados entre sí.",
        "ppal_status_agregados": "Se agregaron {n} tema(s) nuevo(s) ({dup} duplicado(s) omitido(s)).",
        "ppal_status_saltear_on": "Se va a saltear",
        "ppal_status_saltear_off": "Se vuelve a reproducir",
        "ppal_status_tema_reanudado": "▶ Tema recordado de la sesión anterior, reanudado en {seg}s.",
        "ppal_status_tema_cargado_pausado": "▶ Tema recordado de la sesión anterior, cargado en {seg}s (pausado, tocá ▶ para seguir).",
        "ppal_status_detenido_pausado": "⏹ Detenido (pausado). Presioná Detener de nuevo para sacar los temas de las bandejas y volver al principio de la lista.",
        "ppal_status_mezcla_adelantada_sig": "⏭ Mezcla adelantada a la próxima frase: mezclará en cuanto llegue ahí.",
        "ppal_status_mezcla_adelantada_ant": "⏮ Mezcla anterior adelantada a la próxima frase: mezclará en cuanto llegue ahí.",
        "ppal_banner_analizando_fondo": "🎧 Analizando temas en segundo plano...",
        "ppal_banner_ordenando_tono": "🎧 Ordenando por tono en segundo plano...",
        "ppal_banner_analizando_progreso": "🎧 Analizando temas en segundo plano... ({listos}/{total})",
        "ppal_overlay_buscando_duplicados": "🔎 Buscando duplicados...",
        "ppal_overlay_cargando_temas": "⏳ Cargando temas, esperá un momento... ({actual}/{total})",
        "ppal_msgbox_limpiar_titulo": "Limpiar lista completa",
        "ppal_msgbox_limpiar_texto": "¿Eliminar todos los {n} temas?",
        "ppal_msgbox_no_eliminar_titulo": "No se puede eliminar",
        "ppal_msgbox_no_eliminar_sonando": "Esa pista está sonando ahora mismo.",
        "ppal_msgbox_no_eliminar_carpeta_sonando": "Uno de los temas de esa carpeta está sonando ahora mismo.",

        # --- Ventana de la lista de temas (Lista.py) ---
        "lista_tooltip_saltear": "Saltear este tema: se queda en la lista pero el avance\nautomático lo salta, como si no estuviera (se lo puede\nseguir reproduciendo a mano con doble click).",
        "lista_ventana_titulo": "🎵 Lista de temas: {n}",
        "lista_tooltip_aleatorio_on": "Modo aleatorio ACTIVADO: los temas se van sorteando sin repetir. Click para volver al orden normal de la lista.",
        "lista_tooltip_aleatorio_off": "Orden normal. Click para activar el modo aleatorio (los temas se van sorteando sin repetir hasta agotar la lista).",

        # --- Ajustes: paneles individuales y editor de skins (Stage 3) ---
        "ajustes_lbl_anterior": "Anterior:",
        "ajustes_lbl_siguiente": "Siguiente:",
        "ajustes_chk_normalizar": "Normalizar automáticamente",
        "ajustes_lbl_nivel": "Nivel:",
        "ajustes_chk_brillo_automatico": "Modo automático",
        "ajustes_lbl_agudo": "Agudo:",
        "ajustes_lbl_golpe": "Golpe:",
        "ajustes_lbl_actual_mejora": "Actual - mejora",
        "ajustes_lbl_agudo_min": "agudo:",
        "ajustes_lbl_golpe_min": "golpe:",
        "ajustes_lbl_mejora_total": "Mejora total:",
        "ajustes_lbl_punto_a": "A:",
        "ajustes_lbl_punto_b": "B:",
        "ajustes_lbl_tiempo_mezcla": "Tiempo Mezcla:",
        "ajustes_lbl_fade_minimo": "   Fade mínimo:",
        "ajustes_chk_filtro": "🎛 Filtro (entra apagado y se abre)",
        "ajustes_chk_eco": "🔉 Eco (delay que se apaga)",
        "ajustes_lbl_intensidad": "Intensidad:",
        "ajustes_lbl_anclaje_b": "Anclaje B:",
        "ajustes_chk_energia_orden": "⚡ Considerar energía en el orden",
        "ajustes_lbl_ordenar_por": "Ordenar por:",
        "ajustes_lbl_al_agregar": "Al agregar:",
        "ajustes_lbl_estilo": "Estilo:",
        "ajustes_chk_golpe_seco_activar": "Activar golpe seco",
        "ajustes_lbl_potencia": "Potencia:",
        "ajustes_lbl_golpe_seco_min": "golpe seco:",
        "skin_editor_titulo": "🎨 Editor de skins -- creando una skin nueva",
        "skin_lbl_ayuda": "Tocá cada flecha de color para cambiarlo. El resultado se ve al instante en toda la app, incluida esta misma ventana.",
        "skin_lbl_cargar_skin": "Cargar skin guardada:",
        "skin_lbl_nombre_skin": "Nombre de la skin:",
        "skin_placeholder_nombre": "Ej: Mi skin azul",
        "skin_combo_nueva_skin": "➕ Nueva skin (Pandemic)",
        "skin_fila_reproduciendo": "▶ Reproduciendo",
        "skin_fila_espera": "⏭ En espera",
        "skin_fila_seleccionada": "🖱 Seleccionada (click)",
        "skin_fila_normal_par": "Tema normal (Par)",
        "skin_fila_normal_impar": "Tema normal (Impar)",
        "skin_fila_saltear": "⛔ Saltear",
        "skin_fondo_lista": "Fondo de la lista",
        "skin_lbl_ayuda_lista": "Cada flecha es del mismo color que la fila que señala --\ntocala para cambiar ese color puntual.",
        "skin_demo_boton": "Botón",
        "skin_demo_combo": "Combo",
        "skin_recuadro_grupo": "Recuadro / grupo",
        "skin_lbl_ayuda_bordes": "\"Botón/Combo\" es el contorno de botones, combos, campos y\nla lista. \"Recuadro/grupo\" es el contorno de los recuadros\nde este mismo panel de Ajustes.",
        "skin_selector_titulo": "Selector",
        "skin_btn_guardar": "💾 Guardar skin",
        "skin_btn_cancelar": "✖ Cancelar",
        "ajustes_lbl_freq_auto": "🎯 Frecuencia del pulso: automática (afinada por tema)",
    },
    "en": {
        "ajustes_titulo_ventana": "⚙ Settings - Smart AI DJ Mixer",
        "ajustes_teclas_titulo": "🎹 Mix keys",
        "ajustes_volumen_titulo": "🔊 Volume",
        "ajustes_brillo_titulo": "✨ Brightness and punch",
        "ajustes_cruce_titulo": "🎚️ Crossfade",
        "ajustes_efectos_titulo": "🎛️ Live effects",
        "ajustes_zona_titulo": "🎯 Mix zone",
        "ajustes_orden_titulo": "🔀 Order and loading",
        "ajustes_estilo_titulo": "🎨 Visual style",
        "ajustes_historial_titulo": "📄 History",
        "ajustes_cerrar_titulo": "✔ Close",
        "ajustes_restaurar_titulo": "↺ Factory defaults",
        "ajustes_golpe_seco_titulo": "🥁 Kick punch",
        "ajustes_idioma_titulo": "🌐 Language",
        "ajustes_idioma_etiqueta": "Language:",
        "ajustes_idioma_nota": "Applied when you restart the program.",
        "boton_cerrar": "Close",
        "boton_restaurar_todo": "↺ Restore all",
        "boton_abrir_carpeta_estilos": "📂 Open styles folder",
        "boton_crear_skin": "🎨 Create skin",
        "boton_exportar_historial": "📄 Export session history",
        "boton_acerca_de": "ℹ️ About",
        "skin_lista_titulo": "Track list -- arrow = which color changes",
        "skin_bordes_titulo": "Borders -- arrow = which color changes",
        "skin_volumen_titulo": "Volume -- arrow = which color changes",

        # --- Main window (SmartDJPlayer / Principal.py) ---
        "ppal_tooltip_minimizar": "Minimize",
        "ppal_tooltip_cerrar_ventana": "Close",
        "ppal_overlay_analizando": "⏳ Analyzing tracks, please wait...",
        "ppal_lista_recuperada": "Playlist restored from last session ({n} tracks).",
        "ppal_lista_vacia_arrastra": "Empty playlist. Drag files here or use 📂 Load folder.",
        "ppal_deck_a_vacio": "Deck A: (no track)",
        "ppal_deck_b_vacio": "Deck B: (no track queued)",
        "ppal_deck_a_nombre": "Deck A",
        "ppal_deck_b_nombre": "Deck B",
        "ppal_sin_datos": "No data",
        "ppal_volumen_master_etiqueta": "Master Volume:",
        "ppal_tooltip_volumen_master": "Overall output volume. Affects A and B equally.",
        "ppal_tooltip_btn_config": "Open Settings (keys, normalizer, brightness, crossfade, effects, order, loading).",
        "ppal_estado_prefijo": "Status",
        "ppal_estado_inicial": "Waiting for music...",
        "ppal_pista_actual_prefijo": "Current track",
        "ppal_pista_actual_ninguna": "None",
        "ppal_tooltip_prev": "Mix to the previous track (moves the marker to the next phrase).",
        "ppal_tooltip_next": "Mix to the next track (moves the marker to the next phrase).",
        "ppal_tooltip_play": "Play / Pause.",
        "ppal_tooltip_stop": "First click: pause (keeps the tracks loaded on the decks).\nSecond click (already stopped): clears the decks and rewinds\nto the start of the playlist.",
        "ppal_btn_limpiar_lista": "🗑 Clear list",
        "ppal_tooltip_limpiar_lista": "Removes all tracks from the playlist (asks for confirmation).",
        "ppal_btn_reordenar_auto": "🔀 Auto-reorder",
        "ppal_tooltip_reordenar_auto": "Re-sorts the whole playlist automatically (by BPM or Key,\nwhichever you chose in Settings) and re-enables auto order,\nwhich turns off when you move tracks by hand.",
        "ppal_btn_ocultar_lista": "📋 Hide list",
        "ppal_btn_mostrar_lista": "📋 Show list",
        "ppal_tooltip_mostrar_lista": "Shows or hides the playlist window (which lives\nseparately, docked below the player by default). If you\ndrag it near any edge of the player it snaps into place\n(magnet) and travels docked from then on; drag it away\nto undock it.",
        "ppal_chk_auto": "Auto",
        "ppal_tooltip_modo_mezcla": "Auto: tracks crossfade into each other once the\nyellow marker is reached (automatic mix mode).\nMan: each track ends and moves straight to the next,\nwith no crossfade or marker (manual mode).",
        "ppal_tooltip_waveform_next": "Drag the yellow marker to manually move the point\nwhere this track enters the next mix.",
        "ppal_tooltip_golpe_seco_barra": "Kick punch: kick-drum energy level (60-120 Hz band)\nof the incoming track, measured live. Lights up on each\nkick and fades between hits.",
        "ppal_status_aleatorio_on": "🔀 Shuffle mode enabled.",
        "ppal_status_aleatorio_off": "☰ Shuffle mode disabled, the list is back to its normal order.",
        "ppal_status_no_audios": "No audio files found in {carpeta}",
        "ppal_status_orden_manual_actualizado": "✋ Manual order updated.",
        "ppal_status_orden_auto_desactivado": "✋ You moved a track by hand. Auto order disabled\n(use 🔀 Auto-reorder to turn it back on).",
        "ppal_status_lista_vacia_ordenar": "No tracks in the list to sort.",
        "ppal_status_orden_auto_tono": "🔀 Auto order re-enabled (by Key).",
        "ppal_status_orden_auto_bpm": "🔀 Auto order re-enabled (by BPM).",
        "ppal_status_lista_vacia": "Empty playlist.",
        "ppal_status_temas_eliminados": "🗑️ Removed {n} tracks from \"{grupo}\".",
        "ppal_status_error_reproducir": "❌ Playback error: {err}",
        "ppal_status_error_inesperado": "❌ Unexpected error: {err}",
        "ppal_status_ordenando_tono_fondo": "🎧 Sorting by key in the background...",
        "ppal_status_todos_saltear": "⛔ Every track in the list is marked to skip.",
        "ppal_status_punto_enganche": "Mix-in point moved to {pct}% of the track. It will be kept for future tracks.",
        "ppal_status_punto_entrada_b": "📍 B's entry point moved by hand ({seg}s). Reprocessing...",
        "ppal_status_nada_nuevo": "Nothing new was added: {n} track(s) were already in the list or duplicated each other.",
        "ppal_status_agregados": "Added {n} new track(s) ({dup} duplicate(s) skipped).",
        "ppal_status_saltear_on": "Will be skipped",
        "ppal_status_saltear_off": "Will play again",
        "ppal_status_tema_reanudado": "▶ Track restored from last session, resumed at {seg}s.",
        "ppal_status_tema_cargado_pausado": "▶ Track restored from last session, loaded at {seg}s (paused, press ▶ to continue).",
        "ppal_status_detenido_pausado": "⏹ Stopped (paused). Press Stop again to clear the decks and rewind to the start of the list.",
        "ppal_status_mezcla_adelantada_sig": "⏭ Mix moved up to the next phrase: it will mix as soon as it gets there.",
        "ppal_status_mezcla_adelantada_ant": "⏮ Previous mix moved up to the next phrase: it will mix as soon as it gets there.",
        "ppal_banner_analizando_fondo": "🎧 Analyzing tracks in the background...",
        "ppal_banner_ordenando_tono": "🎧 Sorting by key in the background...",
        "ppal_banner_analizando_progreso": "🎧 Analyzing tracks in the background... ({listos}/{total})",
        "ppal_overlay_buscando_duplicados": "🔎 Looking for duplicates...",
        "ppal_overlay_cargando_temas": "⏳ Loading tracks, please wait... ({actual}/{total})",
        "ppal_msgbox_limpiar_titulo": "Clear entire playlist",
        "ppal_msgbox_limpiar_texto": "Remove all {n} tracks?",
        "ppal_msgbox_no_eliminar_titulo": "Can't remove this",
        "ppal_msgbox_no_eliminar_sonando": "That track is playing right now.",
        "ppal_msgbox_no_eliminar_carpeta_sonando": "One of the tracks in that folder is playing right now.",

        # --- Playlist window (Lista.py) ---
        "lista_tooltip_saltear": "Skip this track: it stays in the list but auto-advance\nskips over it, as if it weren't there (you can still\nplay it by hand with a double click).",
        "lista_ventana_titulo": "🎵 Track list: {n}",
        "lista_tooltip_aleatorio_on": "Shuffle mode ON: tracks are drawn without repeats.\nClick to go back to the list's normal order.",
        "lista_tooltip_aleatorio_off": "Normal order. Click to enable shuffle mode (tracks are\ndrawn without repeats until the list runs out).",

        # --- Ajustes: paneles individuales y editor de skins (Stage 3) ---
        "ajustes_lbl_anterior": "Previous:",
        "ajustes_lbl_siguiente": "Next:",
        "ajustes_chk_normalizar": "Auto-normalize volume",
        "ajustes_lbl_nivel": "Level:",
        "ajustes_chk_brillo_automatico": "Automatic mode",
        "ajustes_lbl_agudo": "Treble:",
        "ajustes_lbl_golpe": "Bass hit:",
        "ajustes_lbl_actual_mejora": "Current - boosted",
        "ajustes_lbl_agudo_min": "treble:",
        "ajustes_lbl_golpe_min": "bass hit:",
        "ajustes_lbl_mejora_total": "Total boost:",
        "ajustes_lbl_punto_a": "A:",
        "ajustes_lbl_punto_b": "B:",
        "ajustes_lbl_tiempo_mezcla": "Mix Time:",
        "ajustes_lbl_fade_minimo": "   Minimum fade:",
        "ajustes_chk_filtro": "🎛 Filter (starts closed and opens)",
        "ajustes_chk_eco": "🔉 Echo (fading delay)",
        "ajustes_lbl_intensidad": "Intensity:",
        "ajustes_lbl_anclaje_b": "B anchor:",
        "ajustes_chk_energia_orden": "⚡ Consider energy in ordering",
        "ajustes_lbl_ordenar_por": "Sort by:",
        "ajustes_lbl_al_agregar": "When adding:",
        "ajustes_lbl_estilo": "Style:",
        "ajustes_chk_golpe_seco_activar": "Enable punch",
        "ajustes_lbl_potencia": "Power:",
        "ajustes_lbl_golpe_seco_min": "punch:",
        "skin_editor_titulo": "🎨 Skin editor -- creating a new skin",
        "skin_lbl_ayuda": "Tap each color arrow to change it. The result shows instantly across the whole app, including this window.",
        "skin_lbl_cargar_skin": "Load saved skin:",
        "skin_lbl_nombre_skin": "Skin name:",
        "skin_placeholder_nombre": "E.g.: My blue skin",
        "skin_combo_nueva_skin": "➕ New skin (Pandemic)",
        "skin_fila_reproduciendo": "▶ Playing",
        "skin_fila_espera": "⏭ Up next",
        "skin_fila_seleccionada": "🖱 Selected (click)",
        "skin_fila_normal_par": "Regular track (Even)",
        "skin_fila_normal_impar": "Regular track (Odd)",
        "skin_fila_saltear": "⛔ Skip",
        "skin_fondo_lista": "List background",
        "skin_lbl_ayuda_lista": "Each arrow matches the color of the row it points to --\ntap it to change that specific color.",
        "skin_demo_boton": "Button",
        "skin_demo_combo": "Combo",
        "skin_recuadro_grupo": "Box / group",
        "skin_lbl_ayuda_bordes": "\"Button/Combo\" is the outline of buttons, combo boxes,\nfields and the list. \"Box/group\" is the outline of the\nboxes in this same Settings panel.",
        "skin_selector_titulo": "Selector",
        "skin_btn_guardar": "💾 Save skin",
        "skin_btn_cancelar": "✖ Cancel",
        "ajustes_lbl_freq_auto": "🎯 Punch frequency: automatic (tuned per track)",
    },
    "pt": {
        "ajustes_titulo_ventana": "⚙ Configurações - Smart AI DJ Mixer",
        "ajustes_teclas_titulo": "🎹 Teclas de mixagem",
        "ajustes_volumen_titulo": "🔊 Volume",
        "ajustes_brillo_titulo": "✨ Brilho e batida",
        "ajustes_cruce_titulo": "🎚️ Transição",
        "ajustes_efectos_titulo": "🎛️ Efeitos ao vivo",
        "ajustes_zona_titulo": "🎯 Zona de mixagem",
        "ajustes_orden_titulo": "🔀 Ordem e carregamento",
        "ajustes_estilo_titulo": "🎨 Estilo visual",
        "ajustes_historial_titulo": "📄 Histórico",
        "ajustes_cerrar_titulo": "✔ Fechar",
        "ajustes_restaurar_titulo": "↺ Valores de fábrica",
        "ajustes_golpe_seco_titulo": "🥁 Batida seca",
        "ajustes_idioma_titulo": "🌐 Idioma",
        "ajustes_idioma_etiqueta": "Idioma:",
        "ajustes_idioma_nota": "Aplicado ao reiniciar o programa.",
        "boton_cerrar": "Fechar",
        "boton_restaurar_todo": "↺ Restaurar tudo",
        "boton_abrir_carpeta_estilos": "📂 Abrir pasta de estilos",
        "boton_crear_skin": "🎨 Criar skin",
        "boton_exportar_historial": "📄 Exportar histórico da sessão",
        "boton_acerca_de": "ℹ️ Sobre",
        "skin_lista_titulo": "Lista de faixas -- seta = qual cor muda",
        "skin_bordes_titulo": "Bordas -- seta = qual cor muda",
        "skin_volumen_titulo": "Volume -- seta = qual cor muda",

        # --- Janela principal (SmartDJPlayer / Principal.py) ---
        "ppal_tooltip_minimizar": "Minimizar",
        "ppal_tooltip_cerrar_ventana": "Fechar",
        "ppal_overlay_analizando": "⏳ Analisando faixas, aguarde um momento...",
        "ppal_lista_recuperada": "Lista recuperada da sessão anterior ({n} faixas).",
        "ppal_lista_vacia_arrastra": "Lista vazia. Arraste arquivos ou use 📂 Carregar pasta.",
        "ppal_deck_a_vacio": "Deck A: (sem faixa)",
        "ppal_deck_b_vacio": "Deck B: (sem faixa em espera)",
        "ppal_deck_a_nombre": "Deck A",
        "ppal_deck_b_nombre": "Deck B",
        "ppal_sin_datos": "Sem dados",
        "ppal_volumen_master_etiqueta": "Volume Master:",
        "ppal_tooltip_volumen_master": "Volume geral da saída. Afeta A e B igualmente.",
        "ppal_tooltip_btn_config": "Abrir Configurações (teclas, normalizador, brilho, transição, efeitos, ordem, carregamento).",
        "ppal_estado_prefijo": "Status",
        "ppal_estado_inicial": "Aguardando música...",
        "ppal_pista_actual_prefijo": "Faixa atual",
        "ppal_pista_actual_ninguna": "Nenhuma",
        "ppal_tooltip_prev": "Mixar para a faixa anterior (adianta o marcador para a próxima frase).",
        "ppal_tooltip_next": "Mixar para a próxima faixa (adianta o marcador para a próxima frase).",
        "ppal_tooltip_play": "Reproduzir / Pausar.",
        "ppal_tooltip_stop": "Primeiro clique: pausa (mantém as faixas carregadas).\nSegundo clique (já parado): esvazia os decks e volta\npara o início da lista.",
        "ppal_btn_limpiar_lista": "🗑 Limpar lista",
        "ppal_tooltip_limpiar_lista": "Remove todas as faixas da lista (pede confirmação).",
        "ppal_btn_reordenar_auto": "🔀 Reordenar automaticamente",
        "ppal_tooltip_reordenar_auto": "Reordena toda a lista automaticamente (por BPM ou Tom,\no que estiver escolhido nas Configurações) e reativa a\nordem automática, que se desliga quando você move faixas manualmente.",
        "ppal_btn_ocultar_lista": "📋 Ocultar lista",
        "ppal_btn_mostrar_lista": "📋 Mostrar lista",
        "ppal_tooltip_mostrar_lista": "Mostra ou oculta a janela da lista de faixas (que fica\nseparada, encaixada abaixo do player por padrão). Se você\na aproximar de qualquer borda do player, ela se encaixa\nsozinha (ímã) e viaja encaixada dali em diante; se solta\narrastando para longe.",
        "ppal_chk_auto": "Auto",
        "ppal_tooltip_modo_mezcla": "Auto: as faixas se mixam com transição ao chegar no\nmarcador amarelo (modo de mixagem automática).\nMan: cada faixa termina e passa direto para a próxima,\nsem transição nem marcador (modo manual).",
        "ppal_tooltip_waveform_next": "Arraste o marcador amarelo para mover manualmente o ponto\nonde esta faixa entra na próxima mixagem.",
        "ppal_tooltip_golpe_seco_barra": "Batida seca: nível de energia do bumbo (banda 60-120 Hz)\nda faixa que está entrando, medido ao vivo. Acende a cada\nbatida e diminui entre uma e outra.",
        "ppal_status_aleatorio_on": "🔀 Modo aleatório ativado.",
        "ppal_status_aleatorio_off": "☰ Modo aleatório desativado, a lista volta à ordem normal.",
        "ppal_status_no_audios": "Nenhum áudio encontrado em {carpeta}",
        "ppal_status_orden_manual_actualizado": "✋ Ordem manual atualizada.",
        "ppal_status_orden_auto_desactivado": "✋ Você moveu uma faixa manualmente. Ordem automática\ndesativada (use 🔀 Reordenar automaticamente para reativá-la).",
        "ppal_status_lista_vacia_ordenar": "Não há faixas na lista para ordenar.",
        "ppal_status_orden_auto_tono": "🔀 Ordem automática reativada (por Tom).",
        "ppal_status_orden_auto_bpm": "🔀 Ordem automática reativada (por BPM).",
        "ppal_status_lista_vacia": "Lista vazia.",
        "ppal_status_temas_eliminados": "🗑️ Foram removidas {n} faixas de \"{grupo}\".",
        "ppal_status_error_reproducir": "❌ Erro ao reproduzir: {err}",
        "ppal_status_error_inesperado": "❌ Erro inesperado: {err}",
        "ppal_status_ordenando_tono_fondo": "🎧 Ordenando por tom em segundo plano...",
        "ppal_status_todos_saltear": "⛔ Todas as faixas da lista estão marcadas para pular.",
        "ppal_status_punto_enganche": "Ponto de entrada movido para {pct}% da faixa. Será salvo para as próximas faixas.",
        "ppal_status_punto_entrada_b": "📍 Ponto de entrada de B movido manualmente ({seg}s). Reprocessando...",
        "ppal_status_nada_nuevo": "Nada novo foi adicionado: {n} faixa(s) já estavam na lista ou eram duplicadas entre si.",
        "ppal_status_agregados": "Foram adicionadas {n} faixa(s) nova(s) ({dup} duplicada(s) ignorada(s)).",
        "ppal_status_saltear_on": "Vai ser pulada",
        "ppal_status_saltear_off": "Vai voltar a tocar",
        "ppal_status_tema_reanudado": "▶ Faixa lembrada da sessão anterior, retomada em {seg}s.",
        "ppal_status_tema_cargado_pausado": "▶ Faixa lembrada da sessão anterior, carregada em {seg}s (pausada, toque ▶ para continuar).",
        "ppal_status_detenido_pausado": "⏹ Parado (pausado). Pressione Parar novamente para esvaziar os decks e voltar ao início da lista.",
        "ppal_status_mezcla_adelantada_sig": "⏭ Mixagem adiantada para a próxima frase: vai mixar assim que chegar lá.",
        "ppal_status_mezcla_adelantada_ant": "⏮ Mixagem anterior adiantada para a próxima frase: vai mixar assim que chegar lá.",
        "ppal_banner_analizando_fondo": "🎧 Analisando faixas em segundo plano...",
        "ppal_banner_ordenando_tono": "🎧 Ordenando por tom em segundo plano...",
        "ppal_banner_analizando_progreso": "🎧 Analisando faixas em segundo plano... ({listos}/{total})",
        "ppal_overlay_buscando_duplicados": "🔎 Procurando duplicadas...",
        "ppal_overlay_cargando_temas": "⏳ Carregando faixas, aguarde um momento... ({actual}/{total})",
        "ppal_msgbox_limpiar_titulo": "Limpar lista completa",
        "ppal_msgbox_limpiar_texto": "Remover todas as {n} faixas?",
        "ppal_msgbox_no_eliminar_titulo": "Não é possível remover",
        "ppal_msgbox_no_eliminar_sonando": "Essa faixa está tocando agora.",
        "ppal_msgbox_no_eliminar_carpeta_sonando": "Uma das faixas dessa pasta está tocando agora.",

        # --- Janela da lista de faixas (Lista.py) ---
        "lista_tooltip_saltear": "Pular esta faixa: ela continua na lista, mas o avanço\nautomático a pula, como se não estivesse ali (ainda dá\npara tocá-la manualmente com um duplo clique).",
        "lista_ventana_titulo": "🎵 Lista de faixas: {n}",
        "lista_tooltip_aleatorio_on": "Modo aleatório ATIVADO: as faixas vão sendo sorteadas\nsem repetir. Clique para voltar à ordem normal da lista.",
        "lista_tooltip_aleatorio_off": "Ordem normal. Clique para ativar o modo aleatório (as\nfaixas vão sendo sorteadas sem repetir até esgotar a lista).",

        # --- Ajustes: paneles individuales y editor de skins (Stage 3) ---
        "ajustes_lbl_anterior": "Anterior:",
        "ajustes_lbl_siguiente": "Próxima:",
        "ajustes_chk_normalizar": "Normalizar automaticamente",
        "ajustes_lbl_nivel": "Nível:",
        "ajustes_chk_brillo_automatico": "Modo automático",
        "ajustes_lbl_agudo": "Agudo:",
        "ajustes_lbl_golpe": "Grave:",
        "ajustes_lbl_actual_mejora": "Atual - melhorado",
        "ajustes_lbl_agudo_min": "agudo:",
        "ajustes_lbl_golpe_min": "grave:",
        "ajustes_lbl_mejora_total": "Melhoria total:",
        "ajustes_lbl_punto_a": "A:",
        "ajustes_lbl_punto_b": "B:",
        "ajustes_lbl_tiempo_mezcla": "Tempo de mixagem:",
        "ajustes_lbl_fade_minimo": "   Fade mínimo:",
        "ajustes_chk_filtro": "🎛 Filtro (entra fechado e vai abrindo)",
        "ajustes_chk_eco": "🔉 Eco (delay que vai apagando)",
        "ajustes_lbl_intensidad": "Intensidade:",
        "ajustes_lbl_anclaje_b": "Ancoragem B:",
        "ajustes_chk_energia_orden": "⚡ Considerar energia na ordem",
        "ajustes_lbl_ordenar_por": "Ordenar por:",
        "ajustes_lbl_al_agregar": "Ao adicionar:",
        "ajustes_lbl_estilo": "Estilo:",
        "ajustes_chk_golpe_seco_activar": "Ativar impacto seco",
        "ajustes_lbl_potencia": "Potência:",
        "ajustes_lbl_golpe_seco_min": "impacto seco:",
        "skin_editor_titulo": "🎨 Editor de skins -- criando uma skin nova",
        "skin_lbl_ayuda": "Toque em cada seta de cor para mudá-la. O resultado aparece na hora em todo o app, incluindo esta janela.",
        "skin_lbl_cargar_skin": "Carregar skin salva:",
        "skin_lbl_nombre_skin": "Nome da skin:",
        "skin_placeholder_nombre": "Ex: Minha skin azul",
        "skin_combo_nueva_skin": "➕ Nova skin (Pandemic)",
        "skin_fila_reproduciendo": "▶ Tocando",
        "skin_fila_espera": "⏭ Em espera",
        "skin_fila_seleccionada": "🖱 Selecionada (clique)",
        "skin_fila_normal_par": "Faixa normal (Par)",
        "skin_fila_normal_impar": "Faixa normal (Ímpar)",
        "skin_fila_saltear": "⛔ Pular",
        "skin_fondo_lista": "Fundo da lista",
        "skin_lbl_ayuda_lista": "Cada seta tem a mesma cor da linha que indica --\ntoque nela para mudar essa cor específica.",
        "skin_demo_boton": "Botão",
        "skin_demo_combo": "Combo",
        "skin_recuadro_grupo": "Quadro / grupo",
        "skin_lbl_ayuda_bordes": "\"Botão/Combo\" é o contorno de botões, combos, campos e\na lista. \"Quadro/grupo\" é o contorno dos quadros deste\nmesmo painel de Configurações.",
        "skin_selector_titulo": "Seletor",
        "skin_btn_guardar": "💾 Salvar skin",
        "skin_btn_cancelar": "✖ Cancelar",
        "ajustes_lbl_freq_auto": "🎯 Frequência do impacto: automática (ajustada por faixa)",
    },
}

_idioma_actual = IDIOMA_POR_DEFECTO


def establecer_idioma(codigo: str) -> None:
    """Cambia el idioma activo para toda la app (afecta las próximas
    llamadas a tr()). No reconstruye por sí solo ventanas ya abiertas
    -- cada pantalla que quiera actualizarse en caliente debe volver a
    llamar tr() sobre sus propios widgets (ver _retranslar_ajustes)."""
    global _idioma_actual
    if codigo in TEXTOS:
        _idioma_actual = codigo


def idioma_actual() -> str:
    return _idioma_actual


def tr(clave: str) -> str:
    """Devuelve el texto de `clave` en el idioma activo. Si falta en
    ese idioma cae al español, y si tampoco está ahí devuelve la
    clave tal cual (para notar fácil una traducción que falte)."""
    return (TEXTOS.get(_idioma_actual, {}).get(clave)
            or TEXTOS["es"].get(clave)
            or clave)
